name: Truffle tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --save-dev truffle
      - run: npm install --save-dev solidity-coverage
      - run: npx truffle run coverage
  gas-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --save-dev truffle
      - run: npm install --save-dev eth-gas-reporter
      - run: npx truffle test
